apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-key-service
  namespace: api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-key-service
  template:
    metadata:
      labels:
        app: api-key-service
    spec:
      containers:
      - name: api-key-service
        image: api-key-service:latest
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres:5432/apikeys?sslmode=disable"
        - name: REDIS_URL
          value: "redis://redis:6379"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-key-service
  namespace: api-proxy
spec:
  selector:
    app: api-key-service
  ports:
  - port: 8080
    targetPort: 8080